# Use custom format
format='$time$shlvl$jobs$directory$character'
right_format = '$golang$lua$rust$dart$nodejs$python$git_branch$git_status'

scan_timeout = 10
add_newline = false

# continuation_prompt = "â–¶â–¶"

[jobs]
format='$number$symbol$style'
symbol=' ï‘µ  '
number_threshold=2
symbol_threshold=1
style='green'
disabled=true

[directory]
read_only = "ï«º "
style="bold green"
home_symbol = "ï½"

[character]
success_symbol="[ï” ](bold cyan)"
error_symbol="[ï” ](red)"
vicmd_symbol="[ï„ ](yellow)"

[fill]
symbol='â•'
style='red'
disabled=true

[aws]
symbol = "îŒ½ "
format = ' \[[$symbol($profile) (\( $region \)) (\[ $duration \])]($style) \] '

[cmake]
format = '\[ [$symbol($version)]($style)\] '

[cmd_duration]
format = "[$duration]($style)"
disabled=true

[conda]
symbol = " ï„Œ  "
format = '\[ [$symbol $environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = " î˜ "
format = '\[[$symbol($version)]($style) \]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
symbol = " ïŒˆ  "
format = ' \[[$symbol $context]($style) \] '

[dotnet]
format = '\[[$symbol($version)(ğŸ¯ $tfm)]($style)\]'

[elixir]
symbol = " î‰µ "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = " î˜¬ "
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol=""
format='[\[](bold cyan)[$symbol$branch]($style)[\]](bold cyan)'
style='italic yellow'

[git_status]
format ='([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = "î˜§ "
format = '\[ [$symbol($version)]($style) \] '

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = "ï˜  "
format = ' \[[$symbol$branch]($style)\] '

[java]
symbol = "î‰– "
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = "î˜¤ "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = ' \[[ $symbol $context (\($namespace\) )]($style)\ ] '

[lua]
format = '\[ [$symbol($version)]($style) \]'

[memory_usage]
symbol = "ï¡š "
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nim]
symbol = "ïš¤ "
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = "ï‹œ "
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = ' \[ [$symbol ($version)]($style) \] '

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
symbol = "ï£– "
format = '[\[](bold black) [$symbol$version]($style) [\]](bold black)'
style = 'yellow'

[perl]
symbol = "î© "
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = "î˜ˆ "
format = ' \[ [$symbol ($version)]($style) \] '

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = "î˜† "
format = ' \[ [${symbol} ${pyenv_prefix} (${version}) (\( $virtualenv \))]($style) \] '

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = "îˆ¾ "
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = "î¨ "
format = ' \[ [$symbol ($version)]($style) \] '

[scala]
symbol = "îœ· "
format = '\[[$symbol($version)]($style)\]'

[shlvl]
disabled=false
symbol = "ï„  "
format = '\[ [$symbol $shlvl]($style) \] '
threshold = 1

[swift]
symbol = "ï¯£ "
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
disabled=true
format = '[$time]($style) '
style = 'bold white'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
